export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const CHANGE_CURRENT_LINK = "CHANGE_CURRENT_LINK";
export const FETCH_ERROR = "FETCH_ERROR";
export const CLEAR_CURRENT_LINK = "CLEAR_CURRENT_LINK";
export const SET_CURRENT_LINK = "SET_CURRENT_LINK";